name: Testing
run-name: ${{ github.actor }} is running the test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Test
        uses: nathanheffley/laravel-phpunit-action@master
