name: check code quality
run-name: ${{ github.actor }} check code quality
on: [push, workflow_dispatch]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: laravel/pint

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check code style using laravel/pint
        run: pint --test
